name: Build and deploy dotnet core project to Azure Function App - funtionprocessorfile-dev-linux

on:
  push:
    branches:
      - feature/file-processing-service
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x' # set this to the dotnet version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: 'Upload Build Artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: functionapp
          path: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: 'Download Build Artifacts'
        uses: actions/download-artifact@v3
        with:
          name: functionapp
          path: './output'

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2D1FF30588EA49BDADC18AF8100BF36B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0404B9CF00414DD083BE87ECE9EDA2E7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3E9ED45F64BF405A8BC540FAAF173ECC }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'funtionprocessorfile-dev-linux'
          slot-name: 'development'
          package: './output'